Repository javascript-tutorial/de.javascript.info, pull requests merged in 2020-04, with the labels that each got.

#26 Logical operators
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/solution.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
  1-js/02-first-steps/11-logical-operators/8-if-question/task.md
  1-js/02-first-steps/11-logical-operators/9-check-login/ifelse_task.svg
  1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
  1-js/02-first-steps/11-logical-operators/9-check-login/task.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: needs +1, review needed

#14 Operators
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/1-increment-order/task.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/task.md
  1-js/02-first-steps/07-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/07-operators/3-primitive-conversions-questions/task.md
  1-js/02-first-steps/07-operators/article.md
Labels: review needed

#30 German translation Arrow functions, the basics
  1-js/02-first-steps/16-arrow-functions-basics/1-rewrite-arrow/solution.md
  1-js/02-first-steps/16-arrow-functions-basics/1-rewrite-arrow/task.md
  1-js/02-first-steps/16-arrow-functions-basics/article.md
Labels: ready to merge
